# Generated by Django 5.1.4 on 2024-12-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdiems', '0002_alter_servicebill_bill_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestservice',
            name='accounting_signature',
        ),
        migrations.RemoveField(
            model_name='requestservice',
            name='applicant_signature',
        ),
        migrations.RemoveField(
            model_name='requestservice',
            name='supervisor_signature',
        ),
        migrations.AddField(
            model_name='requestservice',
            name='accounting_signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/accounting/'),
        ),
        migrations.AddField(
            model_name='requestservice',
            name='applicant_signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/applicant/'),
        ),
        migrations.AddField(
            model_name='requestservice',
            name='supervisor_signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/supervisor/'),
        ),
    ]
