# Generated by Django 5.1.4 on 2024-12-31 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdiems', '0006_servicebill_bill_class_servicebill_bill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestservice',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicebill',
            name='bill_class',
            field=models.CharField(blank=True, choices=[('ALIMENTACION', 'Alimentacion'), ('HOSPEDAJE', 'Hospedaje'), ('GASOLINA', 'GASOLINA'), ('PASAJE', 'Pasaje')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='servicebill',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('FACTURA', 'Factura'), ('BOLETA', 'Boleta'), ('RECIBO', 'Recibo'), ('TICKET', 'Ticket'), ('PLANILLA_MOVILIDAD', 'Planilla movilidad')], max_length=20, null=True),
        ),
    ]
