# Generated by Django 5.1.4 on 2024-12-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_dailyexchangerate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_route', models.CharField(default='', max_length=20)),
                ('end_route', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
